export type TDocumentoNormativo = {
	numero: string
	nombre: string
	tipo: string
	fecha: string
	descripcion?: string
	archivoUrl: string
	thumbnailUrl?: string
	badge?: { label: string; color: string }
}

export const DOCUMENTOS_NORMATIVOS: TDocumentoNormativo[] = [
	{
		numero: "16",
		nombre: "COMUNICADO: La UGEL La Convención convoca a la inscripción para la Evaluación Excepcional de Dominio de Lengua Originaria (EDLO) 2026. 🇵🇪✨",
		tipo: "Comunicado",
		fecha: "2026-03-02",
		descripcion: "📢 Si eres docente y aún no estás en el RND-Bilingües, ¡esta es tu oportunidad para la etapa excepcional de contrato!, ¡Solo tienes dos días! 👉 02 y 03 de marzo de 2026. Link: https://forms.gle/Gy1Dwx4p7yCeuJu88",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/16.comunicado-eib-f-02032026.jpg",		
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "15",
		nombre: "MEMORANDUM MULTIPLE N°014-2026-GORE-C/GEREDU-C/DUGEL-LC/SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-02-27",
		descripcion: "📢 Comunica a Directores(as) de las Instituciones educativas públicas del ámbito de la Ugel La Convención, la llegada de material educativo a las II.EE - Dotación 2026 e implementación de pautas para su recepción.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N°014-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-27022026.pdf",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "14",
		nombre: "OFICIO MULTIPLE N°06-2026-GORE-C/DRE-C/DUGE-LC/D.",
		tipo: "Oficio Múltiple",
		fecha: "2026-02-26",
		descripcion: "📢 Convoca a Directores(as) de las Instituciones educativas públicas y privadas de los niveles inicial, primaria, secundaria, ceba, cebe, cetpro del ámbito de la Ugel La Convención, a la asistencia técnica para reforzar las orientaciones respecto al Plan de Gestión de riesgos, Brigadas de GRD, Soporte Socioemocional para el año 2026, evento que se realizara el día viernes 27/02/2026 en el  3:00 p.m a 4:30 p.m via virtual.",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/OFICIO%20MULTIPLE%20N°07-2026-GORE-CDRE-CDUGE-LC-D-F-26022026.pdf",		
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "13",
		nombre: "COMUNICADO: INVITACIÓN A ASISTENCIA TECNICA - MI Mantenimiento",
		tipo: "Comunicado",
		fecha: "2026-02-25",
		descripcion: "📢 Precisiones para el correcto registro de la ficha de acciones en el sistema MI MANTENIMIENTO 2026.",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/comunicado-mi-mantenimiento-f-25022026.jpeg",		
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "12",
		nombre: "OFICIO MÚLTIPLE N.º 00025-2026-MINEDU/VMGP-DIGEIBIRA",
		tipo: "Oficio Múltiple",
		fecha: "2026-02-23",
		descripcion: "Convocatoria para el proceso de inscripción a la Evaluación del Dominio de la Lengua Indígena u Originaria de Docentes (EDLO 2026)",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/OFICIO%20MÚLTIPLE%20N.º%2000025-2026-MINEDUVMGP-DIGEIBIRA.pdf",		
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "11",
		nombre: "SEMANA DE LA INNOVACIÓN: PROYECTOS QUE INSPIRAN, PRÁCTICAS QUE TRANSFORMAN - 2026.",
		tipo: "Comunicado",
		fecha: "2026-02-13",
		descripcion: "Estimados(as) Directores(as) de las II. EE. del ámbito de la UGEL La Convención, reciban un cordial saludo. Se les invita a participar en la Videoconferencia sobre la Semana de la Innovación, espacio orientado a fortalecer la cultura innovadora, compartir experiencias y brindar orientaciones para la implementación de acciones innovadoras en sus instituciones educativas 🗓 Fecha : Lunes 16 de febrero 🕒 Hora : 8:30 a 10:30 a.m 💻 Modalidad : Virtual 🔗 Enlace : » Clic para Ingresar al Zoom",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N008-2026-GORE-C-DRE-C-DUGE-LC-SEC-F-11022026.pdf",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "10",
		nombre: "MM-N008-2026-GORE-C-DRE-C-DUGE-LC-SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-02-11",
		descripcion: "Se convoca a los directivos de los niveles Inicial, Primaria y Secundaria a participar en la Jornada de Reflexión y Asistencia Tecnica Presencial organizado por la UGEL La Convención, evento a realizarse los días 23,24 y 25 de febrero según cronograma adjunto al presente documento.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N008-2026-GORE-C-DRE-C-DUGE-LC-SEC-F-11022026.pdf",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "09",
		nombre: "MM-N007-2026-GORE-C-DRE-C-DUGE-LC-SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-02-11",
		descripcion: "Se convoca a los directivos de los niveles Inicial, Primaria y Secundaria a participar en el Taller Presencial organizado por la UGEL La Convención, evento a realizarse según cronograma adjunto al presente documento.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N007-2026-GORE-C-DRE-C-DUGE-LC-SEC-F-11022026.pdf",		
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "08",
		nombre: "OFICIO-MULTIPLE-N03-2026-GORE-C-DRE-C-DUGE-LC.",
		tipo: "Oficio Múltiple",
		fecha: "2026-02-11",
		descripcion: "Se convoca con carácter de MUY URGENTE a los Directores(as) de las II.EE. de todos los niveles (Inicial, Primaria, Secundaria, CEBA, CEBE, CETPRO) y coordinadores de PRONOEI ante la declaratoria de Estado de Emergencia (D.S. N° 003-2026-PCM) por intensas precipitaciones.",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/OFICIO-MULTIPLE-N03-2026-GORE-C-DRE-C-DUGE-LC-D-11022026.pdf",		
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "07",
		nombre: "MM-004-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC.",
		tipo: "Oficio Múltiple",
		fecha: "2026-02-11",
		descripcion: "Se convoca a los directivos de los niveles Inicial, Primaria y Secundaria a participar en los próximos talleres virtuales enfocados en fortalecer la educación a través de la ciencia y la creatividad, Fechas: Del martes 16 al jueves 18 de febrero de 2026. Horario: 8:30 a.m. a 10:30 a.m. Plataforma: Zoom (el enlace se compartirá mediante los grupos oficiales de WhatsApp, Organiza: Comité de Investigación e Innovación del Área de AGP - UGEL La Convención.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N05-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-11022026.pdf",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "06",
		nombre: "MM-004-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-02-11",
		descripcion:"Comunica a Directores de las Instituciones Educativas Polidocentes del nivel Inicial. Primaria y Secundaria que ya se encuentra habilitado en la Plataforma SIMON el Inst-714 del BIAE 2026 Fase 1-Autoreporte el cual deberán cumplir en hacer el llenado del formulario en mención entre el 11 al 28 de febrero para el cual se estará brindano las orientaciones respectivas el día 16 de febrero en una reunión virtual que se llevara a cabo a partir de las 10:00 a.m",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N009-GORE-C-GEREDU-C-DUGEL.LC-SEC-F-11022026.pdf",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "05",
		nombre: "MM-004-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-02-09",
		descripcion:"Convoca a participar en la Asistencia Tecnica Virtual denominada Fortalecimiento de la Gestión Directiva e Incremento de Matriculas de Niñas y Niños de 3 años de la UGEL La Convención - 2026, evento a realizarse el día 10 de febrero del 2026 en el horario de 4:00 p.m a 5:00 p.m.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/OM-N°004-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-09022026.pdf",
	},
	{
		numero: "04",
		nombre: "OM-049-2026-GORE-C-GEREDU-C-DUGEL-LC-JAGP-SEC.",
		tipo: "Oficio Múltiple",
		fecha: "2026-02-03",
		descripcion:"Comunica a Directores de las II.EE, Promover la preinscripción y garantizar la participación de las y los auxiliares de educación de Instituciones Educativas de su jurisdicción en el curso virtual “Agentes de cambio por la inclusión”, segunda edición, a través del portal web de PerúEduca",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/OFICIO-MULTIPLE-00009-2026-MINEDU-VMGI-DIGC-DIF-F-04022026.pdf",
	},
	{
		numero: "03",
		nombre: "¡ATENCIÓN BENEFICIARIOS DE LA DEUDA SOCIAL!.",
		tipo: "Comunicado",
		fecha: "2026-01-09",
		descripcion:"Lista de Beneficiarios que deben enviar su numero de cuenta.",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/COMUNICADO-DEUDA-SOCIAL-F-21012026.png",
	},
	{
		numero: "02",
		nombre: "MM-N003-2026-GR-C-GEREDU-C-D-UGEL-LC-JAGP-SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-01-14",
		descripcion:"Convoca a Directores de las II.EE del Nivel Inicial, Primaria, Secundaria, EBE y EBA del ambito de la UGEL La Convención, a participar en el lanzamiento oficial del proyecto educativo regional PER al 2036 en la Provincia de la Convencion.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N003-2026-GR-C-GEREDU-C-D-UGEL-LC-JAGP-SEC-F-14012026.pdf",
	},
	{
		numero: "01",
		nombre: "Comunicado Mi Mantenimiento",
		tipo: "Comunicado",
		fecha: "2026-01-09",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/COMUNICADO-REGISTRO-DE-DIRECTORES-2026-MI-MANTENIMIENTO-F-09012026.pdf",
	},
]
