export type TDocumentoNormativo = {
	numero: string
	nombre: string
	tipo: string
	fecha: string
	descripcion?: string
	archivoUrl: string
	thumbnailUrl?: string
	enlace?: string
	badge?: { label: string; color: string }
}

export const DOCUMENTOS_NORMATIVOS: TDocumentoNormativo[] = [
	
	{
		numero: "37",
		nombre: "MEMORÁNDUM MÚLTIPLE N°048-2026-GORE-C-DUGEL-LC-SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-04-20",
		descripcion: "📢 Convoca a Directores(as) de los niveles de Inicial, Primaria y Secundaria, y Docentes Coordinadores de PRONOEI a la Asistencia Técnica Virtual denominada Plan de capacitación virtual para el registro de recepción y asignación de materiales educativos en el módulo SIAGIE - Dotación 2026",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/37.MM-N48-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-20042026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "36",
		nombre: "MEMORÁNDUM MÚLTIPLE N°247-GR CUSCO/GEREDU.",
		tipo: "Oficio Múltiple",
		fecha: "2026-04-17",
		descripcion: "📢 Comunica a Directores de las Intituciones Educativas pulicas y privadas de la ciudad de Quillabamba, la participación en la celebración dia internacional de la madre tierra a realizarse el 22 de abril del 2026, en la plaza de armas de la ciudad de Quillabamba a las 8:00 a.m.",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/36.OM-N13-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-17042026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "35",
		nombre: "MEMORÁNDUM MÚLTIPLE N°247-GR CUSCO/GEREDU.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-04-09",
		descripcion: "📢 Traslada comunicación sobre disponibilidad de locales escolares para el proceso electoral del 12 de abril de 2026.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/35.MM-N247-2026-GR-CUSCO-GEREDU-F-09042026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "34",
		nombre: "MEMORÁNDUM MÚLTIPLE N°237-GR CUSCO/GEREDU.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-04-09",
		descripcion: "📢 Traslada Convocatoria para comisionados electorales y voluntarios de la defensoria del pueblo, con el objeto de supervisar las elecciones generales del 12 de abril en el ambito de la Region.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/34.MM-N237-2026-GR-CUSCO-GEREDU-F-09042026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "33",
		nombre: "MEMORÁNDUM MÚLTIPLE N°00036-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-04-09",
		descripcion: "📢 Comunica a Directores de las Instituciones Educativas del ambito de la UGEL La Convención, las acciones urgentes para garantizar la matricula de niños de 3 años en su institución educativa.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/33.MM-N°036-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-09042026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "32",
		nombre: "MEMORÁNDUM MÚLTIPLE N°00035-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-04-08",
		descripcion: "📢 Comunica a Directores de las Instituciones Educativas del ambito de la UGEL La Convención el fortalecimiento de la identidad institucional mediante el cambio de nombre de las instituciones educativas públicas",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/32.MM-035-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-08042026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},

	{
		numero: "31",
		nombre: "OFICIO N°060-2025-GERESA-RSSLC-D.E-DAIS-PROMSA",
		tipo: "Oficio Múltiple",
		fecha: "2026-04-07",
		descripcion: "📢 Comunica certificación a docentes asistentes a los talleres de estilos de vida saludable",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/31.OFICIO.N°060-2025-GERESA-RSSLC-D.E-DAIS-PROMSA-F-07042026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},

	{
		numero: "30",
		nombre: "MEMORÁNDUM MÚLTIPLE N°00037-2026-GORE-C-DRE-C-DUGE-LC-DAGP-SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-04-07",
		descripcion: "📢 Comunica la validación de directores y docentes asesores de Clubes de Ciencia y Tecnologia -SIGECCYT CONCYTEC",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/30.MM-00036-2026-GORE-C-DRE-C-DUGE-LC-DAGP-SEC-F-07042026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},

	{
		numero: "29",
		nombre: "MEMORÁNDUM MÚLTIPLE N°00037-2026-GORE-C-DRE-C-DUGE-LC-DAGP-SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-04-07",
		descripcion: "📢 Convoca a ATA Virtual de la normatica RVM N°034-2022-MINEDU diriguida a los directores docentes PIP y personal CIST, evento a realizarse el día miercoles 15 de abril en el horario de 15:00 p.m a 16:30 p.m",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/29.MM-00037-2026-GORE-C-DRE-C-DUGE-LC-DAGP-SEC-F-07042026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},

	{
		numero: "28",
		nombre: "MEMORÁNDUM MÚLTIPLE N°00038-2026-GORE-C-DRE-C-DUGE-LC-DAGP-SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-04-07",
		descripcion: "📢 Comunica certificación a docentes participantes en talleres de estilos saludables 2025.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/28.MM-00038-2026-GORE-C-DRE-C-DUGE-LC-DAGP-SEC-F-07042026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "27",
		nombre: "OFICIO MÚLTIPLE N°00050-2026-GORE-C-DRE-C-DUGE-LC-DAGP-SEC",
		tipo: "Oficio Múltiple",
		fecha: "2026-04-07",
		descripcion: "📢 Invita a participación en curso virtual gratuito 'Inteligencia Artificial' para la Pedagogía, el curso se desarrollara los días 15, 16 y 17 de abril del presente año.",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/27.OM-N00050-2026-GORE-C-DRE-C-DUGE-LC-DAGP-SEC-F-07042026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "26",
		nombre: "MEMORÁNDUM MÚLTIPLE N°029-2026- GORE-C/GEREDU-C/DUGEL-LC/SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-03-30",
		descripcion: "📢 Convoca a Directores de las II.EEE del Ambito de la UGEL La Convencion a la reunión virtual sobre el Uso y manejo del Sistema de Asistencia Docente y Administrativo 2026, evento a realizarse el dia miercoles 01/04/2026 a partir de las 3:30 p.m",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/26.MM-N29-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-30032026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "25",
		nombre: "OFICIO MÚLTIPLE N.º 00047-2026-MINEDU/VMGP-DIGEIBIRA",
		tipo: "Oficio Múltiple",
		fecha: "2026-03-24",
		descripcion: "📢 Modificación de cronograma del proceso de Evaluación de Dominio de la Lengua Indígena u Originaria de Docentes (EDLO) 2026.",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/25.OFICIO-MULTIPLE-00047-2026-MINEDU-VMGP-DIGEIBIRA-F-24032026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "24",
		nombre: "Memorandum Multiple N°023-2026-GORE-C-DRE-C-DUGEL-LC-SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-03-17",
		descripcion: "📢 Remite a Directores(as) de las instituciones educativas publicas no escolarizadas de Educación Inicial (a partir de los 03 años), primaria y secundaria del ámbito de la UGEL La Convención, la información sobre la programación del menu escolar 2026, pra el servicio alimentario escolar en las II.EE.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/24.MM-023-2026-GORE-C-DRE-C-DUGE-LC-SEC-F-17032026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "23",
		nombre: "Oficio Multiple N°010-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC",
		tipo: "Oficio Múltiple",
		fecha: "2026-03-17",
		descripcion: "📢 Comunica a Directores(as) de las instituciones educativas publicas del ámbito de la UGEL La Convención, al taller de capacitación sobre la actividad de Geolocalización 2026 de locales educativos, evento a realizarse el día jueves 19 de marzo del 2026.",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/23.OM-N°010-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-17032026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "22",
		nombre: "Memorandum Multiple N°019-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-03-16",
		descripcion: "📢 Comunica a Directores(as) de las instituciones educativas publicas de los niveles inicial, primaria, secundaria, ceba, cebe, del ámbito de la UGEL La Convención, cumplir con el registro de AUTO REPORTE plan de Monitoreo - 361 Instrumento 721 (Carácter de Declaración Jurada) del 16 de Marzo al 05 de Abril.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/22.MM-021-2026-GORE-C-DRE-C-DUGE-LC-SEC-F-16032026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "21",
		nombre: "Memorandum Multiple N°019-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-03-12",
		descripcion: "📢 Comunica a Directores(as) de las instituciones educativas publicas de los niveles inicial, primaria, secundaria, ceba, cebe, CETPRO y coordinadores de PRONOEI del ámbito de la UGEL La Convención, la remisión de informe en caso la IE haya sido afectada por peligros naturales ante declaratoria por peligro inminente.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/21.OM-N08-2026-GORE-C-DRE-C-DUGE-LC-D-F-12032026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "20",
		nombre: "Memorandum Multiple N°019-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-03-11",
		descripcion: "📢 Convoca a Directores de las II.EE publicas y programas no escolarizados de educación inicial (a partir de los 3 años), primaria y secundaria focalizadas del ambito de la UGEL La Convención a participar de la 1ra edición del curso virtual EL CAE Y LA PRESTACIÓN DEL SERVICIO ALIMENTARIO ESCOLAR, diriguido a los docentes integrantes de los comite de alimentación escolar (CAE).",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/20.MM-N19-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-11032026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "19",
		nombre: "Comunicado Evaluación Excepcional de Lenguas originarias 2026",
		tipo: "Comunicado",
		fecha: "2026-03-04",
		descripcion: "📢 La Unidad de Gestión Educativa Local La Convención comunica a los docentes inscritos APTOS para la Evaluación Excepcional de Dominio de Lengua Originaria (EDLO) 2026 que dicha evaluación se desarrollará de acuerdo con el siguiente detalle.",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/19.DOCENTES-APTOS-PARA-EVALUACION-EXCEPCIONAL-DE-DOMINIO-DE-LENGUA-ORIGINARIA-F-05032026.pdf",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "18",
		nombre: "Memorandum Multiple N°105-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-03-04",
		descripcion: "📢 Comunica a Directores de las Intituciones Educativas del ámbito de la UGEL La Convención, brindar facilidades para la participación en reunión de reflexión y asamblea provincial convocada para el día viernes 06 de marzo de 2026 a las 08:00 a.m.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/18.MM-N015–2026-GORE-CGEREDU-CDUGEL-LC-SEC-04032026.PDF",
		enlace:"",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "17",
		nombre: "Memorandum Multiple N°122-2026-GR-CUSCO-GEREDU",
		tipo: "Memorandum Múltiple",
		fecha: "2026-03-02",
		descripcion: "📢 Traslada comunicación de publicación del FED 2025-2026 en la Pagina Web del FED , Categoria Educación",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/17.MM-N122-2026-GR-CUSCO-GEREDU-F-02032026.pdf",
		enlace:"https://www.gob.pe/73526-ministerio-de-educacion-fondo-de-estimulo-al-desempeno-y-logro-de-resultados-sociales-fed-categoria-educacion",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "16",
		nombre: "COMUNICADO: La UGEL La Convención convoca a la inscripción para la Evaluación Excepcional de Dominio de Lengua Originaria (EDLO) 2026. 🇵🇪✨",
		tipo: "Comunicado",
		fecha: "2026-03-02",
		descripcion: "📢 Si eres docente y aún no estás en el RND-Bilingües, ¡esta es tu oportunidad para la etapa excepcional de contrato!, ¡Solo tienes dos días! 👉 02 y 03 de marzo de 2026.",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/16.comunicado-eib-f-02032026.jpg",
		enlace:"https://forms.gle/Gy1Dwx4p7yCeuJu88",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "15",
		nombre: "MEMORANDUM MULTIPLE N°014-2026-GORE-C/GEREDU-C/DUGEL-LC/SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-02-27",
		descripcion: "📢 Comunica a Directores(as) de las Instituciones educativas públicas del ámbito de la Ugel La Convención, la llegada de material educativo a las II.EE - Dotación 2026 e implementación de pautas para su recepción.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N°014-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-27022026.pdf",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "14",
		nombre: "OFICIO MULTIPLE N°06-2026-GORE-C/DRE-C/DUGE-LC/D.",
		tipo: "Oficio Múltiple",
		fecha: "2026-02-26",
		descripcion: "📢 Convoca a Directores(as) de las Instituciones educativas públicas y privadas de los niveles inicial, primaria, secundaria, ceba, cebe, cetpro del ámbito de la Ugel La Convención, a la asistencia técnica para reforzar las orientaciones respecto al Plan de Gestión de riesgos, Brigadas de GRD, Soporte Socioemocional para el año 2026, evento que se realizara el día viernes 27/02/2026 en el  3:00 p.m a 4:30 p.m via virtual.",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/OFICIO%20MULTIPLE%20N°07-2026-GORE-CDRE-CDUGE-LC-D-F-26022026.pdf",		
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "13",
		nombre: "COMUNICADO: INVITACIÓN A ASISTENCIA TECNICA - MI Mantenimiento",
		tipo: "Comunicado",
		fecha: "2026-02-25",
		descripcion: "📢 Precisiones para el correcto registro de la ficha de acciones en el sistema MI MANTENIMIENTO 2026.",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/comunicado-mi-mantenimiento-f-25022026.jpeg",		
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "12",
		nombre: "OFICIO MÚLTIPLE N.º 00025-2026-MINEDU/VMGP-DIGEIBIRA",
		tipo: "Oficio Múltiple",
		fecha: "2026-02-23",
		descripcion: "Convocatoria para el proceso de inscripción a la Evaluación del Dominio de la Lengua Indígena u Originaria de Docentes (EDLO 2026)",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/OFICIO%20MÚLTIPLE%20N.º%2000025-2026-MINEDUVMGP-DIGEIBIRA.pdf",		
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "11",
		nombre: "SEMANA DE LA INNOVACIÓN: PROYECTOS QUE INSPIRAN, PRÁCTICAS QUE TRANSFORMAN - 2026.",
		tipo: "Comunicado",
		fecha: "2026-02-13",
		descripcion: "Estimados(as) Directores(as) de las II. EE. del ámbito de la UGEL La Convención, reciban un cordial saludo. Se les invita a participar en la Videoconferencia sobre la Semana de la Innovación, espacio orientado a fortalecer la cultura innovadora, compartir experiencias y brindar orientaciones para la implementación de acciones innovadoras en sus instituciones educativas 🗓 Fecha : Lunes 16 de febrero 🕒 Hora : 8:30 a 10:30 a.m 💻 Modalidad : Virtual 🔗 Enlace : » Clic para Ingresar al Zoom",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N008-2026-GORE-C-DRE-C-DUGE-LC-SEC-F-11022026.pdf",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "10",
		nombre: "MM-N008-2026-GORE-C-DRE-C-DUGE-LC-SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-02-11",
		descripcion: "Se convoca a los directivos de los niveles Inicial, Primaria y Secundaria a participar en la Jornada de Reflexión y Asistencia Tecnica Presencial organizado por la UGEL La Convención, evento a realizarse los días 23,24 y 25 de febrero según cronograma adjunto al presente documento.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N008-2026-GORE-C-DRE-C-DUGE-LC-SEC-F-11022026.pdf",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "09",
		nombre: "MM-N007-2026-GORE-C-DRE-C-DUGE-LC-SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-02-11",
		descripcion: "Se convoca a los directivos de los niveles Inicial, Primaria y Secundaria a participar en el Taller Presencial organizado por la UGEL La Convención, evento a realizarse según cronograma adjunto al presente documento.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N007-2026-GORE-C-DRE-C-DUGE-LC-SEC-F-11022026.pdf",		
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "08",
		nombre: "OFICIO-MULTIPLE-N03-2026-GORE-C-DRE-C-DUGE-LC.",
		tipo: "Oficio Múltiple",
		fecha: "2026-02-11",
		descripcion: "Se convoca con carácter de MUY URGENTE a los Directores(as) de las II.EE. de todos los niveles (Inicial, Primaria, Secundaria, CEBA, CEBE, CETPRO) y coordinadores de PRONOEI ante la declaratoria de Estado de Emergencia (D.S. N° 003-2026-PCM) por intensas precipitaciones.",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/OFICIO-MULTIPLE-N03-2026-GORE-C-DRE-C-DUGE-LC-D-11022026.pdf",		
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "07",
		nombre: "MM-004-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC.",
		tipo: "Oficio Múltiple",
		fecha: "2026-02-11",
		descripcion: "Se convoca a los directivos de los niveles Inicial, Primaria y Secundaria a participar en los próximos talleres virtuales enfocados en fortalecer la educación a través de la ciencia y la creatividad, Fechas: Del martes 16 al jueves 18 de febrero de 2026. Horario: 8:30 a.m. a 10:30 a.m. Plataforma: Zoom (el enlace se compartirá mediante los grupos oficiales de WhatsApp, Organiza: Comité de Investigación e Innovación del Área de AGP - UGEL La Convención.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N05-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-11022026.pdf",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	{
		numero: "06",
		nombre: "MM-004-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC",
		tipo: "Memorandum Múltiple",
		fecha: "2026-02-11",
		descripcion:"Comunica a Directores de las Instituciones Educativas Polidocentes del nivel Inicial. Primaria y Secundaria que ya se encuentra habilitado en la Plataforma SIMON el Inst-714 del BIAE 2026 Fase 1-Autoreporte el cual deberán cumplir en hacer el llenado del formulario en mención entre el 11 al 28 de febrero para el cual se estará brindano las orientaciones respectivas el día 16 de febrero en una reunión virtual que se llevara a cabo a partir de las 10:00 a.m",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N009-GORE-C-GEREDU-C-DUGEL.LC-SEC-F-11022026.pdf",
		badge: { label: "Nuevo", color: "#10b981" },
	},
	
	{
		numero: "05",
		nombre: "MM-004-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-02-09",
		descripcion:"Convoca a participar en la Asistencia Tecnica Virtual denominada Fortalecimiento de la Gestión Directiva e Incremento de Matriculas de Niñas y Niños de 3 años de la UGEL La Convención - 2026, evento a realizarse el día 10 de febrero del 2026 en el horario de 4:00 p.m a 5:00 p.m.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/OM-N°004-2026-GORE-C-GEREDU-C-DUGEL-LC-SEC-F-09022026.pdf",
	},
	{
		numero: "04",
		nombre: "OM-049-2026-GORE-C-GEREDU-C-DUGEL-LC-JAGP-SEC.",
		tipo: "Oficio Múltiple",
		fecha: "2026-02-03",
		descripcion:"Comunica a Directores de las II.EE, Promover la preinscripción y garantizar la participación de las y los auxiliares de educación de Instituciones Educativas de su jurisdicción en el curso virtual “Agentes de cambio por la inclusión”, segunda edición, a través del portal web de PerúEduca",
		thumbnailUrl: "/assets/images/publicaciones/oficio-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/OFICIO-MULTIPLE-00009-2026-MINEDU-VMGI-DIGC-DIF-F-04022026.pdf",
	},
	{
		numero: "03",
		nombre: "¡ATENCIÓN BENEFICIARIOS DE LA DEUDA SOCIAL!.",
		tipo: "Comunicado",
		fecha: "2026-01-09",
		descripcion:"Lista de Beneficiarios que deben enviar su numero de cuenta.",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/COMUNICADO-DEUDA-SOCIAL-F-21012026.png",
	},
	{
		numero: "02",
		nombre: "MM-N003-2026-GR-C-GEREDU-C-D-UGEL-LC-JAGP-SEC.",
		tipo: "Memorandum Múltiple",
		fecha: "2026-01-14",
		descripcion:"Convoca a Directores de las II.EE del Nivel Inicial, Primaria, Secundaria, EBE y EBA del ambito de la UGEL La Convención, a participar en el lanzamiento oficial del proyecto educativo regional PER al 2036 en la Provincia de la Convencion.",
		thumbnailUrl: "/assets/images/publicaciones/memorandum-multiple.png",
		archivoUrl: "/assets/files/2026/publicaciones/MM-N003-2026-GR-C-GEREDU-C-D-UGEL-LC-JAGP-SEC-F-14012026.pdf",
	},
	{
		numero: "01",
		nombre: "Comunicado Mi Mantenimiento",
		tipo: "Comunicado",
		fecha: "2026-01-09",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/COMUNICADO-REGISTRO-DE-DIRECTORES-2026-MI-MANTENIMIENTO-F-09012026.pdf",
	},
	{
		numero: "00",
		nombre: "CUADRO MULTIANUAL DE NECESIDADES APROBADO UNIDAD DE GESTIÓN EDUCATIVA LOCAL LA CONVENCIÓN",
		tipo: "Documento",
		fecha: "2026-01-09",
		thumbnailUrl: "/assets/images/publicaciones/comunicado.png",
		archivoUrl: "/assets/files/2026/publicaciones/CUADRO-MULTIANUAL-NCESIDADES-UGEL-LC-APROBADO-2026.pdf",
	},
]
